using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Common generation settings shared by local and cloud-backed profiles.
/// </summary>
public abstract class BaseLlmGenerationProfile : ScriptableObject
{
    [Header("Shared Generation Settings")]
    public string format;
    public bool stream;
    public string keepAlive;

    [TextArea(3, 20)]
    [Tooltip("System prompt template; supports {{varName}} placeholders.")]
    public string systemPromptTemplate;

    [Tooltip("How JSON schema constraints are delivered to the model: strict grammar decoding, prompt append fallback, or automatic mode.")]
    public JsonSchemaDeliveryMode jsonSchemaDeliveryMode = JsonSchemaDeliveryMode.Auto;

    [Tooltip("Thinking mode control for Qwen3-series models.")]
    public ThinkingMode thinkingMode = ThinkingMode.Disabled;

    [SerializeField]
    [Tooltip("Structured definition that drives the JSON format enforced at runtime.")]
    private List<JsonFieldDefinition> jsonFields = new();

    public LlmGenerationProfile.ModelParams modelParams = new LlmGenerationProfile.ModelParams();

    [NonSerialized]
    private string _lastRenderedPrompt;

    public IReadOnlyList<JsonFieldDefinition> JsonFields => jsonFields;
    public bool IsThinkingEnabled => thinkingMode != ThinkingMode.Disabled;
    public JsonSchemaDeliveryMode EffectiveJsonSchemaDeliveryMode => jsonSchemaDeliveryMode;

    protected virtual void OnValidate()
    {
        jsonFields ??= new List<JsonFieldDefinition>();
        modelParams ??= new LlmGenerationProfile.ModelParams();
        RebuildFormatFromFields();
    }

    /// <summary>
    /// Forces the format string to match the structured JSON field definitions.
    /// </summary>
    public void RebuildFormatFromFields()
    {
        format = JsonFieldDefinition.BuildSchema(jsonFields);
    }

    /// <summary>
    /// Renders the system prompt with the given state dictionary and stores the result for later reuse.
    /// </summary>
    public void RenderSystemPrompt(PipelineState state)
    {
        var tmpl = new PromptTemplate(systemPromptTemplate ?? string.Empty);
        _lastRenderedPrompt = tmpl.Render(state);
    }

    /// <summary>
    /// Returns the most recently rendered prompt that was generated by RenderSystemPrompt.
    /// </summary>
    public string GetLastRenderedPrompt()
    {
        return _lastRenderedPrompt;
    }
}
