using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.Json;
using UnityEngine;

[CreateAssetMenu(fileName = "LlmGenerationProfile", menuName = "LLM/Generation Profile")]
public class LlmGenerationProfile : ScriptableObject
{
    [Header("Basic Settings")]
    [Tooltip("GGUF model path. Absolute path, or relative to StreamingAssets when enabled in Runtime Params.")]
    public string model = "Models/model.gguf";
    public string format;
    public bool stream = false;
    public string keepAlive = null;
    [Tooltip("Optional multimodal projector / mmproj file required for local vision inference.")]
    public string visionProjectorModel;
    [Tooltip("When true, the vision projector path is resolved from Application.streamingAssetsPath.")]
    public bool visionProjectorRelativeToStreamingAssets = true;

    [TextArea(3, 20)]
    [Tooltip("System prompt template; supports {{varName}} placeholders.")]
    public string systemPromptTemplate;

    [Tooltip("How JSON schema constraints are delivered to the model: strict grammar decoding, prompt append fallback, or automatic mode.")]
    public JsonSchemaDeliveryMode jsonSchemaDeliveryMode = JsonSchemaDeliveryMode.Auto;

    [Tooltip("Thinking mode control for Qwen3-series models.")]
    public ThinkingMode thinkingMode = ThinkingMode.Disabled;

    [SerializeField]
    [Tooltip("Structured definition that drives the JSON format enforced at runtime.")]
    private List<JsonFieldDefinition> jsonFields = new();

    [Serializable]
    public class ModelParams
    {
        public float temperature = 0.7f;
        public float top_p = 0.9f;
        public float top_k = 40f;
        public int num_predict = 0;
        public float repeat_penalty = 1.1f;
        [Min(0)]
        [Tooltip("0 keeps random sampling. Values greater than 0 force a deterministic seed.")]
        public int seed = 0;
    }

    [Serializable]
    public class RuntimeParams
    {
        [Tooltip("When true, model path is resolved from Application.streamingAssetsPath.")]
        public bool modelPathRelativeToStreamingAssets = true;

        [Min(128)]
        public int contextSize = 2048;

        [Min(0)]
        public int gpuLayerCount = 0;

        [Min(0)]
        public int threads = 0;
    }

    public ModelParams modelParams = new ModelParams();
    public RuntimeParams runtimeParams = new RuntimeParams();

    [NonSerialized]
    private string _lastRenderedPrompt;

    public IReadOnlyList<JsonFieldDefinition> JsonFields => jsonFields;
    public bool IsThinkingEnabled => thinkingMode != ThinkingMode.Disabled;
    public JsonSchemaDeliveryMode EffectiveJsonSchemaDeliveryMode => jsonSchemaDeliveryMode;

    private void OnValidate()
    {
        jsonFields ??= new List<JsonFieldDefinition>();
        runtimeParams ??= new RuntimeParams();
        modelParams ??= new ModelParams();
        RebuildFormatFromFields();
    }

    /// <summary>
    /// Forces the format string to match the structured JSON field definitions.
    /// </summary>
    public void RebuildFormatFromFields()
    {
        format = JsonFieldDefinition.BuildSchema(jsonFields);
    }

    /// <summary>
    /// Renders the system prompt with the given state dictionary and stores the result for later reuse.
    /// </summary>
    public void RenderSystemPrompt(PipelineState state)
    {
        var tmpl = new PromptTemplate(systemPromptTemplate ?? string.Empty);
        _lastRenderedPrompt = tmpl.Render(state);
    }

    /// <summary>
    /// Returns the most recently rendered prompt that was generated by RenderSystemPrompt.
    /// </summary>
    public string GetLastRenderedPrompt()
    {
        return _lastRenderedPrompt;
    }

    public string ResolveVisionProjectorPath()
    {
        if (string.IsNullOrWhiteSpace(visionProjectorModel))
        {
            return null;
        }

        string candidate = visionProjectorModel.Trim();
        if (Path.IsPathRooted(candidate))
        {
            return candidate;
        }

        if (visionProjectorRelativeToStreamingAssets)
        {
            return Path.Combine(Application.streamingAssetsPath, candidate);
        }

        return Path.GetFullPath(candidate);
    }
}

public enum JsonSchemaDeliveryMode
{
    Auto = 0,
    GrammarOnly = 1,
    PromptAppendOnly = 2
}

public enum ThinkingMode
{
    Disabled = 0,
    StripThink = 1,
    PreserveThink = 2
}

[Serializable]
public class JsonFieldDefinition
{
    public string fieldName = "field";
    public JsonFieldType fieldType = JsonFieldType.String;
    public JsonArrayElementType arrayElementType = JsonArrayElementType.String;
    [SerializeField]
    public List<JsonFieldDefinition> children = new();
    [SerializeField]
    public List<string> enumOptions = new();
    [SerializeField]
    public string minValue;
    [SerializeField]
    public string maxValue;
    [SerializeField]
    public string minLength;
    [SerializeField]
    public string maxLength;
    [SerializeField]
    public string minItems;
    [SerializeField]
    public string maxItems;

    public static string BuildSchema(List<JsonFieldDefinition> fields)
    {
        if (fields == null || fields.Count == 0)
        {
            return string.Empty;
        }

        var root = BuildObjectSchema(fields);
        return root != null ? JsonSerializer.Serialize(root) : string.Empty;
    }

    private static Dictionary<string, object> BuildObjectSchema(List<JsonFieldDefinition> fields)
    {
        if (fields == null || fields.Count == 0)
        {
            return null;
        }

        var properties = new Dictionary<string, object>(StringComparer.Ordinal);
        var required = new List<string>();

        foreach (var field in fields)
        {
            if (field == null || string.IsNullOrWhiteSpace(field.fieldName))
            {
                continue;
            }

            var schema = BuildSchemaForField(field);
            if (schema == null)
            {
                continue;
            }

            properties[field.fieldName] = schema;
            required.Add(field.fieldName);
        }

        if (properties.Count == 0)
        {
            return null;
        }

        var obj = new Dictionary<string, object>(StringComparer.Ordinal)
        {
            ["type"] = "object",
            ["properties"] = properties,
            ["required"] = required,
            ["additionalProperties"] = false
        };

        return obj;
    }

    private static Dictionary<string, object> BuildSchemaForField(JsonFieldDefinition field)
    {
        Dictionary<string, object> schema;
        Dictionary<string, object> arrayItemSchema = null;
        switch (field.fieldType)
        {
            case JsonFieldType.Object:
                schema = BuildObjectSchema(field.children) ??
                         new Dictionary<string, object>(StringComparer.Ordinal) { ["type"] = "object" };
                break;
            case JsonFieldType.Array:
                schema = new Dictionary<string, object>(StringComparer.Ordinal) { ["type"] = "array" };
                schema["items"] = field.arrayElementType == JsonArrayElementType.Object
                    ? (object)(BuildObjectSchema(field.children) ??
                               new Dictionary<string, object>(StringComparer.Ordinal) { ["type"] = "object" })
                    : (arrayItemSchema = new Dictionary<string, object>(StringComparer.Ordinal)
                    {
                        ["type"] = field.GetArrayItemKeyword()
                    });
                break;
            default:
                schema = new Dictionary<string, object>(StringComparer.Ordinal) { ["type"] = field.GetTypeKeyword() };
                break;
        }

        var enums = NormalizeEnums(field.enumOptions);
        if (enums.Count > 0 && field.fieldType == JsonFieldType.Array && arrayItemSchema != null)
        {
            arrayItemSchema["enum"] = enums;
        }
        else if (enums.Count > 0)
        {
            schema["enum"] = enums;
        }
        else if (field.fieldType == JsonFieldType.Object)
        {
            schema["additionalProperties"] = false;
        }

        AppendNumericBounds(schema, field);
        AppendStringLengthBounds(schema, field);
        AppendArrayItemBounds(schema, field);

        return schema;
    }

    private string GetTypeKeyword()
    {
        return fieldType switch
        {
            JsonFieldType.String => "string",
            JsonFieldType.Number => "number",
            JsonFieldType.Integer => "integer",
            JsonFieldType.Boolean => "boolean",
            JsonFieldType.Object => "object",
            JsonFieldType.Array => "array",
            _ => "string"
        };
    }

    private string GetArrayItemKeyword()
    {
        return arrayElementType switch
        {
            JsonArrayElementType.String => "string",
            JsonArrayElementType.Number => "number",
            JsonArrayElementType.Integer => "integer",
            JsonArrayElementType.Boolean => "boolean",
            JsonArrayElementType.Object => "object",
            _ => "string"
        };
    }

    private static List<string> NormalizeEnums(List<string> enums)
    {
        if (enums == null)
        {
            return new List<string>();
        }

        return enums
            .Where(e => !string.IsNullOrWhiteSpace(e))
            .Select(e => e.Trim())
            .Distinct(StringComparer.Ordinal)
            .ToList();
    }

    private static void AppendNumericBounds(Dictionary<string, object> schema, JsonFieldDefinition field)
    {
        if (schema == null || field == null)
        {
            return;
        }

        bool isNumeric = field.fieldType == JsonFieldType.Number || field.fieldType == JsonFieldType.Integer;
        if (!isNumeric)
        {
            return;
        }

        if (double.TryParse(field.minValue, NumberStyles.Any, CultureInfo.InvariantCulture, out double min))
        {
            schema["minimum"] = min;
        }

        if (double.TryParse(field.maxValue, NumberStyles.Any, CultureInfo.InvariantCulture, out double max))
        {
            schema["maximum"] = max;
        }
    }

    private static void AppendStringLengthBounds(Dictionary<string, object> schema, JsonFieldDefinition field)
    {
        if (schema == null || field == null || field.fieldType != JsonFieldType.String)
        {
            return;
        }

        int? min = TryParseNonNegativeInt(field.minLength);
        int? max = TryParseNonNegativeInt(field.maxLength);

        if (min.HasValue)
        {
            schema["minLength"] = min.Value;
        }

        if (max.HasValue)
        {
            schema["maxLength"] = min.HasValue ? Math.Max(min.Value, max.Value) : max.Value;
        }
    }

    private static void AppendArrayItemBounds(Dictionary<string, object> schema, JsonFieldDefinition field)
    {
        if (schema == null || field == null || field.fieldType != JsonFieldType.Array)
        {
            return;
        }

        int? min = TryParseNonNegativeInt(field.minItems);
        int? max = TryParseNonNegativeInt(field.maxItems);

        if (min.HasValue)
        {
            schema["minItems"] = min.Value;
        }

        if (max.HasValue)
        {
            schema["maxItems"] = min.HasValue ? Math.Max(min.Value, max.Value) : max.Value;
        }
    }

    private static int? TryParseNonNegativeInt(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
        {
            return null;
        }

        if (!int.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out int value))
        {
            return null;
        }

        return value >= 0 ? value : null;
    }
}

public enum JsonFieldType
{
    String = 0,
    Number = 1,
    Integer = 2,
    Boolean = 3,
    Object = 4,
    Array = 5
}

public enum JsonArrayElementType
{
    String = 0,
    Number = 1,
    Integer = 2,
    Boolean = 3,
    Object = 4
}
